name: Deploy

# コンカレンシーの設定
concurrency:
  group: deploy
  cancel-in-progress: false

# この workflow が実行されるタイミング
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 23 * * *"
    - cron: "0 17 * * *"
  workflow_dispatch:
    inputs:
      staging_on:
        description: "Staging ON"
        required: true
        type: boolean
        default: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: [stg, prd]
    env:
      TF_VAR_staging_on: |-
        ${{ 
          (github.event_name == 'push' && 'true') ||
            (
              github.event_name == 'schedule' &&
                (github.event.schedule == '0 23 * * *' && 'true') ||
                'false'
            ) ||
            (github.event_name == 'workflow_dispatch' && inputs.staging_on)
          }}
      TF_VAR_db_user: ${{ secrets.DB_USER }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform init
        run: |
          terraform init

          terraform workspace new ${{ matrix.flavor }}

          terraform workspace select ${{ matrix.flavor }}

      - uses: nick-fields/retry@v2
        name: Deploy
        with:
          timeout_minutes: 60
          max_attempts: 3
          run: |
            terraform apply -auto-approve
          env:
            AWS_PROFILE: ctag-sandbox

